### ISSUE TITLE
Timed Command vs AutoBot

### ISSUE THREAD

**Issue by erich199** [brainfoolong/rwa-timedcommands#1]
Hello,
So I got this working with my rust server. I love it so far. I like being able to send timed messages to advertise the server rules etc. 

Is there a way for this to send a logon message? I would like to send a "Welcome %playername% back to the server"  Is this something the timed commands can do?

Thanks for your help and the great webadmin.

**Comment by brainfoolong** [comment]
This is possible with autobot. As suggest here https://github.com/brainfoolong/rwa-autobot you should just create a script with `log(message)` and than look into your browser console to see what you get when certain things happen in the game.

Noone have currently developed such a autobot script so you have to manage it yourself.

**Comment by erich199** [comment]
Thanks for the fast response.
My server is live and active. When i make the script with the log(message) , it won't spam the server with scripts or messages will it?

**Comment by brainfoolong** [comment]
No, it just show that to you in the browser console.
